// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfuoduupwdknlglqgokx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmdW9kdXVwd2RrbmxnbHFnb2t4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMDM0MjMsImV4cCI6MjA1OTY3OTQyM30.MJ3IHhuStJBMe_LHpm-r_luDbxEZ1JQUTFAI2bdtUqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);